using System;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Windows.Forms;

namespace PROEL_PROJ
{
    public partial class frmReports : Form
    {
        private string connectionString = Classes.ConString();

        public frmReports()
        {
            InitializeComponent();
        }

        private void frmReports_Load_1(object sender, EventArgs e)
        {
            lblUser.Text = Classes.FullName;

            Classes.ApplySidebarStyle(btnDashboard);
            Classes.ApplySidebarStyle(btnStudents);
            Classes.ApplySidebarStyle(btnTeacher);
            Classes.ApplySidebarStyle(btnLogs);
            Classes.ApplySidebarStyle(btnReports);
            Classes.ApplySidebarStyle(btnLogOut);
            Classes.ApplySidebarStyle(btnCourse);

            StyleReportButton(btnActiveStudents);
            StyleReportButton(btnActiveTeachers);
            StyleReportButton(btnAllCourses);
            StyleReportButton(btnStudentsPerCourse);
            StyleReportButton(btnStudentsPerTeacher);

            LoadCoursesDropdown();
            LoadTeachersDropdown();
        }

        private void StyleReportButton(Button btn)
        {
            btn.FlatStyle = FlatStyle.Flat;
            btn.BackColor = Color.FromArgb(41, 128, 185);
            btn.ForeColor = Color.White;
            btn.FlatAppearance.BorderSize = 0;
            btn.FlatAppearance.MouseOverBackColor = Color.FromArgb(52, 152, 219);
            btn.FlatAppearance.MouseDownBackColor = Color.FromArgb(21, 67, 96);
            btn.Cursor = Cursors.Hand;
            btn.Font = new System.Drawing.Font("Segoe UI", 10F, FontStyle.Bold);
        }

        private void LoadCoursesDropdown()
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                string query = @"SELECT CourseID, CourseName FROM Courses WHERE Status = 'ACTIVE' ORDER BY CourseName";
                SqlDataAdapter da = new SqlDataAdapter(query, con);
                DataTable dt = new DataTable();
                da.Fill(dt);

                cmbCourses.DataSource = dt;
                cmbCourses.DisplayMember = "CourseName";
                cmbCourses.ValueMember = "CourseID";
                cmbCourses.SelectedIndex = -1;
            }
        }

        private void LoadTeachersDropdown()
        {
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                string query = @"
                    SELECT 
                        i.InstructorID,
                        CONCAT(p.FirstName, ' ', p.LastName) AS FullName
                    FROM Instructors i
                    INNER JOIN Profiles p ON i.ProfileID = p.ProfileID
                    WHERE p.Status = 'ACTIVE'
                    ORDER BY p.LastName, p.FirstName";

                SqlDataAdapter da = new SqlDataAdapter(query, con);
                DataTable dt = new DataTable();
                da.Fill(dt);

                cmbTeachers.DataSource = dt;
                cmbTeachers.DisplayMember = "FullName";
                cmbTeachers.ValueMember = "InstructorID";
                cmbTeachers.SelectedIndex = -1;
            }
        }

        private void btnActiveStudents_Click_1(object sender, EventArgs e)
        {
            Reports.PrintActiveStudents();
            Logs.Record("Generate Report", $"Active Students report generated by {Logs.CurrentUserName}");
        }

        private void btnActiveTeachers_Click_1(object sender, EventArgs e)
        {
            Reports.PrintActiveTeachers();
            Logs.Record("Generate Report", $"Active Teachers report generated by {Logs.CurrentUserName}");
        }

        private void btnAllCourses_Click_1(object sender, EventArgs e)
        {
            Reports.PrintAllSubjects();
            Logs.Record("Generate Report", $"All Courses report generated by {Logs.CurrentUserName}");
        }

        private void btnStudentsPerCourse_Click_1(object sender, EventArgs e)
        {
            if (cmbCourses.SelectedValue == null)
            {
                MessageBox.Show("Please select a course first.", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            int courseId = Convert.ToInt32(cmbCourses.SelectedValue);
            string courseName = cmbCourses.Text;

            Reports.PrintStudentsPerSubject(courseId, courseName);
            Logs.Record("Generate Report", $"Students per Course report for '{courseName}' generated by {Logs.CurrentUserName}");
        }

        private void btnStudentsPerTeacher_Click_1(object sender, EventArgs e)
        {
            if (cmbTeachers.SelectedValue == null)
            {
                MessageBox.Show("Please select a teacher first.", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            int instructorId = Convert.ToInt32(cmbTeachers.SelectedValue);
            string teacherName = cmbTeachers.Text;

            Reports.PrintStudentsPerTeacher(instructorId, teacherName);
            Logs.Record("Generate Report", $"Students per Teacher report for '{teacherName}' generated by {Logs.CurrentUserName}");
        }

        private void btnDashboard_Click_1(object sender, EventArgs e)
        {
            frmDashboard frmDashboard = new frmDashboard();
            this.Hide();
            frmDashboard.ShowDialog();
        }

        private void btnStudents_Click_1(object sender, EventArgs e)
        {
            frmUpdate_Stud frmUpdate_Stud= new frmUpdate_Stud();
            this.Hide();
            frmUpdate_Stud.ShowDialog();
        }

        private void btnTeacher_Click_1(object sender, EventArgs e)
        {
            frmTeachers frmTeachers = new frmTeachers();
            this.Hide();
            frmTeachers.ShowDialog();
        }

        private void btnCourse_Click_1(object sender, EventArgs e)
        {
            frmCourse frmCourse = new frmCourse();
            this.Hide();
            frmCourse.ShowDialog();
        }

        private void btnLogs_Click_1(object sender, EventArgs e)
        {
            frmLogs frmLogs = new frmLogs();
            this.Hide();
            frmLogs.ShowDialog();
        }

        private void btnLogOut_Click_1(object sender, EventArgs e)
        {
            DialogResult result = MessageBox.Show("Would you like to Log out?", "Confirmation",
            MessageBoxButtons.OKCancel, MessageBoxIcon.Question);
            if (result == DialogResult.OK)
            {
                frmLogIn logIn = new frmLogIn();
                this.Hide();
                logIn.ShowDialog();
            }
            else { }
        }

        private void btnReports_Click(object sender, EventArgs e)
        {

        }
    }
}